Program GERIND;
{FUP QUE A PARTIR DO ARQUIVO cand.txt GERE UM ARQUIVO PARA ACESSO INDEXADO cand.IND
 IRÁ USAR O CONCEITO DE TAMANHO DE REGISTRO QUE POSSUIRÁ OS CAMPOS:
 NUMERO=INTEGER, NOME=STRING[35], CPF=STRING[11], DATA=STRING[8], INVERTIDA AAAAMMDD, CARGO=INTEGER....
 veja bibliont.pas para a descrição completa. (TOTAL DE 816 BITS)
   ATENÇÃO     ATENÇÃO    ATENÇÃO    ATENÇÃO    ATENÇÃO    ATENÇÃO    ATENÇÃO    ATENÇÃO    
  SÓ É POSSIVEL VER O CONTEÚDO DO ARQUIVO ATRAVÉS DE UM PROGRAMA QUE IRÁ LER OS REGISTROS
	}
uses BIBLIONT;
VAR ARQIN:TEXT;
    ARQD:FILE OF REGIS;
    REGIN:STRING[60];
    REGD:REGIS;
    A,B,E,NUM:INTEGER;
Begin
  ASSIGN(ARQIN,'CAND.TXT');
  RESET(ARQIN);
  ASSIGN(ARQD,'CAND.IND');
  REWRITE(ARQD);
  WHILE NOT EOF(ARQIN) DO
   BEGIN
    READLN(ARQIN,REGIN);//RETIRA DO ARQ E LEVA PARA MP AS INFORMAÇOES DE UM REGISTRO (CAND.TXT)
//MONTA O REGISTRO QUE IRÁ PARA ARQD
    VAL(COPY(REGIN,1,4),NUM,E);//RETIRA O NUMERO DO STRING
    REGD.NUM:=NUM;//NUMERO
    REGD.NOME:=COPY(REGIN,5,35);//NOME
    REGD.CPF:=COPY(REGIN,40,11);//CPF
    REGD.DATA.ANO:=copy(regIN,55,4); //ano
    REGD.DATA.MES:=COPY(REGIN,53,2); //mes
    REGD.DATA.DIA:=COPY(REGIN,51,2); //dia
    VAL(COPY(REGIN,59,2),REGD.CAR,E);//CARGO
//POSICIONA
    SEEK(ARQD,A); //<<<<<<COMPARE COM O QUE GERA SAI.DIR (ARQDIR)
//GRAVA NA POSICAO FISICA INDICADA PELO CONTADOR A<<<<<
    WRITE(ARQD,REGD);
		A:=A+1
	 END;
	 WRITELN('GRAVADOS=>',A:5,' REGISTROS--VEJA O TAMANHO DO ARQUIVO -CAND.IND- (ENTER PARA ENCERRAR)');
	 TERMINE;
	 CLOSE(ARQIN);
	 CLOSE(ARQD);  
End.